# This is a basic workflow to help you get started with Actions

name: Main - Test, Coverage and Report

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source code
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.2
        with:
          node-version: 14.17.0
          cache: yarn
      - name: Install Server Dependencies
        run: |
          yarn install
      
      - name: Run Server Tests
        run: |
          yarn test:server:ci

      - name: Publish code coverage
        if: ${{ success() }}
        run: |
          bash <(curl -s https://codecov.io/bash)
      
      - name: Generate Allure Test Report
        uses: simple-elf/allure-report-action@v1.5
        if: always()
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 100
          
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      
      - name: Publish test report to gh-pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.1.12
        env:
          publish_branch: gh-pages
          publish_dir: allure-history
